"""State definitions and models for the Autonomous Remediation Agent Engine."""

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class SeverityLevel(str, Enum):
    """Normalized vulnerability severity levels."""
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    INFO = "INFO"


class FindingType(str, Enum):
    """Source scanner finding type."""
    SAST = "SAST"
    SCA = "SCA"
    SECRET = "SECRET"
    IAC = "IAC"


class RemediationStatus(str, Enum):
    """Lifecycle status of an individual remediation attempt."""
    INITIALIZED = "INITIALIZED"
    TRIAGED = "TRIAGED"
    PATCH_GENERATED = "PATCH_GENERATED"
    VERIFYING = "VERIFYING"
    VERIFIED = "VERIFIED"
    RETRY_NEEDED = "RETRY_NEEDED"
    FAILED = "FAILED"
    PR_READY = "PR_READY"


class Finding(BaseModel):
    """Normalized security finding ingested from SAST or SCA scanners."""
    id: str = Field(description="Unique finding identifier")
    scanner: str = Field(description="Scanner name, e.g. semgrep or trivy")
    finding_type: FindingType = Field(default=FindingType.SAST, description="SAST or SCA")
    rule_id: str = Field(description="Rule or vulnerability identifier (CVE/CWE/Semgrep rule)")
    title: str = Field(description="Short title describing the vulnerability")
    description: str = Field(description="Detailed explanation of the vulnerability")
    severity: SeverityLevel = Field(description="Vulnerability severity level")
    cwe_ids: List[str] = Field(default_factory=list, description="Associated CWE identifiers")
    cvss_score: Optional[float] = Field(default=None, description="CVSS base score if available")
    file_path: str = Field(description="Relative path to the affected file")
    start_line: int = Field(default=1, description="Starting line number")
    end_line: int = Field(default=1, description="Ending line number")
    vulnerable_code: str = Field(default="", description="Target snippet of vulnerable code")
    ast_context: Optional[str] = Field(default=None, description="Surrounding AST context (class, function, imports)")

    # SCA Specific fields
    package_name: Optional[str] = Field(default=None, description="Vulnerable package name (for SCA)")
    installed_version: Optional[str] = Field(default=None, description="Currently installed package version")
    fixed_version: Optional[str] = Field(default=None, description="Target version containing the fix")
    references: List[str] = Field(default_factory=list, description="Reference advisory links")


class VerificationResult(BaseModel):
    """Verification outcome produced by the Verifier Agent."""
    passed: bool = Field(description="Overall verification verdict")
    functional_tests_passed: bool = Field(default=False, description="Did unit/functional tests pass?")
    security_tests_passed: bool = Field(default=False, description="Did security re-scan pass without finding?")
    syntax_valid: bool = Field(default=True, description="Is the generated code syntax valid?")
    test_output: str = Field(default="", description="Standard stdout/stderr from test runner")
    security_scan_output: str = Field(default="", description="Output from post-patch security scan")
    error_message: Optional[str] = Field(default=None, description="Error diagnostics if verification failed")
    duration_seconds: float = Field(default=0.0, description="Verification execution duration")
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class RemediationState(BaseModel):
    """Complete remediation state machine object passing through agent nodes."""
    finding: Finding = Field(description="Target finding being remediated")
    target_repo_path: str = Field(description="Root path to the repository being patched")
    status: RemediationStatus = Field(default=RemediationStatus.INITIALIZED)

    # Patch metadata
    patch_diff: Optional[str] = Field(default=None, description="Unified git diff generated by Patch Agent")
    patch_explanation: Optional[str] = Field(default=None, description="Rationale and mitigation strategy")
    modified_files: List[str] = Field(default_factory=list, description="Files affected by patch")

    # Iteration control
    retry_count: int = Field(default=0, description="Number of patch/verify iterations completed")
    max_retries: int = Field(default=3, description="Maximum allowed feedback iterations")

    # Verification history
    verification_results: List[VerificationResult] = Field(default_factory=list)
    last_error_trace: Optional[str] = Field(default=None, description="Error trace fed back to Patch Agent")

    # PR / Output metadata
    pr_branch: Optional[str] = Field(default=None, description="Git branch name created for the patch")
    pr_title: Optional[str] = Field(default=None, description="Title for Git commit and pull request")
    pr_body: Optional[str] = Field(default=None, description="Detailed markdown PR description")
    commit_sha: Optional[str] = Field(default=None, description="Local or remote commit SHA")

    # Audit log
    audit_trail: List[Dict[str, Any]] = Field(default_factory=list, description="Chronological log of agent steps")
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    updated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    def log_event(self, agent_name: str, action: str, details: Optional[Dict[str, Any]] = None) -> None:
        """Appends a timestamped record to the audit trail."""
        event = {
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "agent": agent_name,
            "action": action,
            "status": self.status.value,
            "details": details or {}
        }
        self.audit_trail.append(event)
        self.updated_at = datetime.now(timezone.utc)
